//go:build !ignore_autogenerated

package crds

import (
	"encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// deepCopyJSON is a helper that deep-copies any JSON-serializable value
// by marshaling and unmarshaling. Used for resources.* Spec types which
// lack generated DeepCopyInto methods.
func deepCopyJSON[T any](src T) T {
	data, err := json.Marshal(src)
	if err != nil {
		return src
	}
	var dst T
	if err := json.Unmarshal(data, &dst); err != nil {
		return src
	}
	return dst
}

func (in *CRDStatus) DeepCopyInto(out *CRDStatus) { *out = *in }
func (in *CRDStatus) DeepCopy() *CRDStatus {
	if in == nil {
		return nil
	}
	out := new(CRDStatus)
	in.DeepCopyInto(out)
	return out
}

// --- Agent ---

func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyJSON(in.Spec)
	out.Status = in.Status
}
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}
func (in *Agent) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Agent, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}
func (in *AgentList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// --- AgentSystem ---

func (in *AgentSystem) DeepCopyInto(out *AgentSystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyJSON(in.Spec)
	out.Status = in.Status
}
func (in *AgentSystem) DeepCopy() *AgentSystem {
	if in == nil {
		return nil
	}
	out := new(AgentSystem)
	in.DeepCopyInto(out)
	return out
}
func (in *AgentSystem) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *AgentSystemList) DeepCopyInto(out *AgentSystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AgentSystem, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *AgentSystemList) DeepCopy() *AgentSystemList {
	if in == nil {
		return nil
	}
	out := new(AgentSystemList)
	in.DeepCopyInto(out)
	return out
}
func (in *AgentSystemList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// --- Tool ---

func (in *Tool) DeepCopyInto(out *Tool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyJSON(in.Spec)
	out.Status = in.Status
}
func (in *Tool) DeepCopy() *Tool {
	if in == nil {
		return nil
	}
	out := new(Tool)
	in.DeepCopyInto(out)
	return out
}
func (in *Tool) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *ToolList) DeepCopyInto(out *ToolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Tool, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ToolList) DeepCopy() *ToolList {
	if in == nil {
		return nil
	}
	out := new(ToolList)
	in.DeepCopyInto(out)
	return out
}
func (in *ToolList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// --- McpServer ---

func (in *McpServer) DeepCopyInto(out *McpServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyJSON(in.Spec)
	out.Status = in.Status
}
func (in *McpServer) DeepCopy() *McpServer {
	if in == nil {
		return nil
	}
	out := new(McpServer)
	in.DeepCopyInto(out)
	return out
}
func (in *McpServer) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *McpServerList) DeepCopyInto(out *McpServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]McpServer, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *McpServerList) DeepCopy() *McpServerList {
	if in == nil {
		return nil
	}
	out := new(McpServerList)
	in.DeepCopyInto(out)
	return out
}
func (in *McpServerList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// --- ModelEndpoint ---

func (in *ModelEndpoint) DeepCopyInto(out *ModelEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyJSON(in.Spec)
	out.Status = in.Status
}
func (in *ModelEndpoint) DeepCopy() *ModelEndpoint {
	if in == nil {
		return nil
	}
	out := new(ModelEndpoint)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelEndpoint) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *ModelEndpointList) DeepCopyInto(out *ModelEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ModelEndpoint, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ModelEndpointList) DeepCopy() *ModelEndpointList {
	if in == nil {
		return nil
	}
	out := new(ModelEndpointList)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelEndpointList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// --- Memory ---

func (in *Memory) DeepCopyInto(out *Memory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyJSON(in.Spec)
	out.Status = in.Status
}
func (in *Memory) DeepCopy() *Memory {
	if in == nil {
		return nil
	}
	out := new(Memory)
	in.DeepCopyInto(out)
	return out
}
func (in *Memory) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *MemoryList) DeepCopyInto(out *MemoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Memory, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *MemoryList) DeepCopy() *MemoryList {
	if in == nil {
		return nil
	}
	out := new(MemoryList)
	in.DeepCopyInto(out)
	return out
}
func (in *MemoryList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// --- AgentPolicy ---

func (in *AgentPolicy) DeepCopyInto(out *AgentPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyJSON(in.Spec)
	out.Status = in.Status
}
func (in *AgentPolicy) DeepCopy() *AgentPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentPolicy)
	in.DeepCopyInto(out)
	return out
}
func (in *AgentPolicy) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *AgentPolicyList) DeepCopyInto(out *AgentPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AgentPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *AgentPolicyList) DeepCopy() *AgentPolicyList {
	if in == nil {
		return nil
	}
	out := new(AgentPolicyList)
	in.DeepCopyInto(out)
	return out
}
func (in *AgentPolicyList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

// --- Secret ---

func (in *Secret) DeepCopyInto(out *Secret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = deepCopyJSON(in.Spec)
	out.Status = in.Status
}
func (in *Secret) DeepCopy() *Secret {
	if in == nil {
		return nil
	}
	out := new(Secret)
	in.DeepCopyInto(out)
	return out
}
func (in *Secret) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *SecretList) DeepCopyInto(out *SecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Secret, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *SecretList) DeepCopy() *SecretList {
	if in == nil {
		return nil
	}
	out := new(SecretList)
	in.DeepCopyInto(out)
	return out
}
func (in *SecretList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
