spring:
  application:
    name: wealth-management
  datasource:
    url: jdbc:hsqldb:mem:wealthdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8080
