{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orloj.fullname" . }}
  labels:
    {{- include "orloj.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secretEncryptionKey }}
  secret-encryption-key: {{ .Values.secretEncryptionKey | quote }}
  {{- end }}
  {{- if .Values.auth.apiToken }}
  api-token: {{ .Values.auth.apiToken | quote }}
  {{- end }}
  {{- if .Values.auth.setupToken }}
  setup-token: {{ .Values.auth.setupToken | quote }}
  {{- end }}
{{- end }}
